name: Deploy

on:
  push:
    branches:
      - "master"
      - "main"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: .env.local

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 23.x
      - run: npm ci
      - run: npm run build
      - run: npm run start
