name: Run Tests

on:
  pull_request:
    branches:
      - "master"
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: .env.local

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 23.x
      - run: npm ci
      - run: npm run build
        env:
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
