name: Run Tests

on:
  pull_request:
    branches:
      - "master"
      - "main"
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 60
    runs-on: self-hosted
    environment: .env.local

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 23.x
      - run: npm ci
      - name: Try to build
        run: npm run build
        env:
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
      - name: Start server
        run: npm run start & npx wait-on https://dyevraq.cimpo1.com/
        env:
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
