on:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 60
    runs-on: self-hosted
    environment: .env.local

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 23.x
      - run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
